{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cnpg-migrator.namespace" . }}
  labels:
    {{- include "cnpg-migrator.labels" . | nindent 4 }}
{{- end }}
